### ISSUE TITLE
Compatibility with future Go versions

### ISSUE THREAD

**Issue by Bo98** [kashav/fsql#45]
Just a heads up that Go 1.17 (and the just-released 1.16 without first changing `GO111MODULE`) won't support builds that aren't in module-aware mode.

The master build should work but the last tag (v0.3.1) does not. Is it possible you can tag a new release for this?

https://blog.golang.org/go116-module-changes

**Comment by kashav** [comment]
Thanks for the heads up. I've created v0.4.0: https://github.com/kashav/fsql/releases/tag/v0.4.0.
