### ISSUE TITLE
Failing darwin builds require a bump of x/sys

### ISSUE THREAD

**Issue by viraptor** [kashav/fsql#46]
Darwin builds are failing with:
```
vendor/golang.org/x/sys/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
```
This can be fixed with `go get -u golang.org/x/sys`, but then the compilation fails on slices which require go >= 1.17.

Could you bump both, please?

**Comment by kashav** [comment]
Thanks for the issue, should be good now.

**Comment by viraptor** [comment]
Awesome, seems to build correctly now, thank you.
